### ISSUE TITLE
StartIndex cannot be less than zero

### ISSUE THREAD

**Issue by Koyakami** [Aionmagan/NSPsplitty#3]
Hi there,

I've been using your application for awhile now for splitting nsp files which has been amazing - thank you! I've just learnt yesterday that it can also merge the files together - godsend.

I've managed to merge alot of files so far however it seems whenever I now try to merge any files I keep getting the same error. (I haven't tried re-doing any I previously done successfully as the parts were deleted afterwards).

folder contains 2 mergeable files
Starting to merge file \00.
 4095MB / 4095MB
 file \00 merged completed.
Starting to merge file \01.
 1327MB / 1327MB
 file \01 merged completed.
StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at NSPsplitty.MainWindow.CopyUnsplit()

Do you have any idea of what the issue is and if I'm able to resolve it? I don't understand it myself.

Many thanks for your great application!

I am using the latest version released on 1st December.

**Comment by Koyakami** [comment]
Nevermind, I just replaced the file.
